version: "3.9"

services:
  app:
    build:
      context: .
      args: 
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - scit-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db 
      - DB_NAME=scit_db
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - scit-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scit_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  scit-db-data:
  scit-static-data: