# Generated by Django 4.1.13 on 2024-05-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
